name: pandas-dev
channels:
  - conda-forge
dependencies:
  # required
  - numpy>=1.16.5
  - python=3
  - python-dateutil>=2.7.3
  - pytz

  # benchmarks
  - asv

  # building
  # The compiler packages are meta-packages and install the correct compiler (activation) packages on the respective platforms.
  - c-compiler
  - cxx-compiler
  - cython>=0.29.21

  # code checks
  - black=20.8b1
  - cpplint
  - flake8
  - flake8-comprehensions>=3.1.0  # used by flake8, linting of unnecessary comprehensions
  - isort>=5.2.1  # check that imports are in the right order
  - mypy=0.782
  - pre-commit>=2.9.2
  - pycodestyle  # used by flake8
  - pyupgrade

  # documentation
  - gitpython  # obtain contributors from git for whatsnew
  - gitdb
  - sphinx

  # documentation (jupyter notebooks)
  - nbconvert>=5.4.1
  - nbsphinx
  - pandoc

  # Dask and its dependencies (that dont install with dask)
  - dask-core
  - toolz>=0.7.3
  - partd>=0.3.10
  - cloudpickle>=0.2.1

  # web (jinja2 is also needed, but it's also an optional pandas dependency)
  - markdown
  - feedparser
  - pyyaml
  - requests

  # testing
  - boto3
  - botocore>=1.11
  - hypothesis>=3.82
  - moto  # mock S3
  - flask
  - pytest>=5.0.1
  - pytest-cov
  - pytest-xdist>=1.21
  - pytest-asyncio
  - pytest-instafail

  # downstream tests
  - seaborn
  - statsmodels

  # unused (required indirectly may be?)
  - ipywidgets
  - nbformat
  - notebook>=5.7.5
  - pip

  # optional
  - blosc
  - bottleneck>=1.2.1
  - ipykernel
  - ipython>=7.11.1
  - jinja2  # pandas.Styler
  - matplotlib>=2.2.2  # pandas.plotting, Series.plot, DataFrame.plot
  - numexpr>=2.6.8
  - scipy>=1.2
  - numba>=0.46.0

  # optional for io
  # ---------------
  # pd.read_html
  - beautifulsoup4>=4.6.0
  - html5lib
  - lxml

  # pd.read_excel, DataFrame.to_excel, pd.ExcelWriter, pd.ExcelFile
  - openpyxl
  - xlrd
  - xlsxwriter
  - xlwt
  - odfpy

  - fastparquet>=0.3.2  # pandas.read_parquet, DataFrame.to_parquet
  - pyarrow>=0.15.0  # pandas.read_parquet, DataFrame.to_parquet, pandas.read_feather, DataFrame.to_feather
  - python-snappy  # required by pyarrow

  - pyqt>=5.9.2  # pandas.read_clipboard
  - pytables>=3.5.1  # pandas.read_hdf, DataFrame.to_hdf
  - s3fs>=0.4.0  # file IO when using 's3://...' path
  - fsspec>=0.7.4  # for generic remote file operations
  - gcsfs>=0.6.0  # file IO when using 'gcs://...' path
  - sqlalchemy  # pandas.read_sql, DataFrame.to_sql
  - xarray  # DataFrame.to_xarray
  - cftime  # Needed for downstream xarray.CFTimeIndex test
  - pyreadstat  # pandas.read_spss
  - tabulate>=0.8.3  # DataFrame.to_markdown
  - natsort  # DataFrame.sort_values
  - pip:
    - git+https://github.com/pandas-dev/pydata-sphinx-theme.git@master
    - git+https://github.com/numpy/numpydoc
